### ISSUE TITLE
iMac Sanp4arduino failed to run

### ISSUE THREAD

**Issue by danadak** [bromagosa/Snap4Arduino#316] opened 2022-12-27 15:12 UTC
> -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nwjs [3246]
Path:                  /private/var/folders/*/Snap4Arduino.app/Contents/MacOS/nwjs
Identifier:            com.nw-builder.snaparduino
Version:               Version 7.0.4 (7.0.4)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-27 10:09:33.9932 -0500
OS Version:            macOS 12.6.2 (21G320)
Report Version:        12
Anonymous UUID:        E340F9B8-87D7-D073-FFC1-12221F22D2A9

Sleep/Wake UUID:       30E4426F-D7D0-43D2-A2B3-1BCB74515469

Time Awake Since Boot: 9500 seconds
Time Since Wake:       4547 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff8059ba00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8059f01ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff80593bd24 abort + 123
3   libsystem_c.dylib             	    0x7ff80593be92 abort_report_np + 180
4   nwjs                          	       0x10f84b9c8 main + 536
5   nwjs                          	       0x10f84b89d main + 237
6   dyld                          	       0x11f4fd52e start + 462

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000011f578600  rcx: 0x00007ff7b06b3768  rdx: 0x0000000000000000
  rdi: 0x0000000000000103  rsi: 0x0000000000000006  rbp: 0x00007ff7b06b3790  rsp: 0x00007ff7b06b3768
   r8: 0x00007ff847143c98   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000000103  r13: 0x00007f80fa804120  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff8059ba00e  rfl: 0x0000000000000246  cr2: 0x000000010f9a5000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

Binary Images:
    0x7ff8059b2000 -     0x7ff8059e9fff libsystem_kernel.dylib (*) <07ad083c-2835-3d18-bb6d-6f081840c8a4> /usr/lib/system/libsystem_kernel.dylib
    0x7ff8059ea000 -     0x7ff8059f5fff libsystem_pthread.dylib (*) <b5454e27-e8c7-3fdb-b77f-714f1e82e70b> /usr/lib/system/libsystem_pthread.dylib
    0x7ff8058ba000 -     0x7ff805942fff libsystem_c.dylib (*) <e42e9d7a-03b4-340b-b61e-dcd45fd4acc0> /usr/lib/system/libsystem_c.dylib
       0x10f84b000 -        0x10f888fff com.nw-builder.snaparduino (Version 7.0.4) <4c4c44d6-5555-3144-a1bb-b4753f1fb10b> /private/var/folders/*/Snap4Arduino.app/Contents/MacOS/nwjs
       0x11f4f8000 -        0x11f563fff dyld (*) <b53641ea-6cd4-39c9-9b14-59c92cfd9584> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=138.9M resident=0K(0%) swapped_out_or_unallocated=138.9M(100%)
Writable regions: Total=26.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=26.1M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            18.1M        9 
MALLOC guard page                   16K        4 
ObjC additional data                15K        1 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                             210K       39 
__DATA_CONST                       288K       33 
__DATA_DIRTY                        58K       22 
__LINKEDIT                       133.9M        4 
__TEXT                            5060K       43 
dyld private memory               1024K        1 
shared memory                        8K        1 
===========                     =======  ======= 
TOTAL                            222.5M      163 

-----------
Full Report
-----------

{"app_name":"nwjs","timestamp":"2022-12-27 10:09:34.00 -0500","app_version":"Version 7.0.4","slice_uuid":"4c4c44d6-5555-3144-a1bb-b4753f1fb10b","build_version":"7.0.4","platform":1,"bundleID":"com.nw-builder.snaparduino","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.2 (21G320)","incident_id":"69773397-6A4F-4B87-8E5D-A45AD707D761","name":"nwjs"}
{
  "uptime" : 9500,
  "procLaunch" : "2022-12-27 10:09:33.9761 -0500",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac16,2",
  "procStartAbsTime" : 9532307663396,
  "coalitionID" : 1246,
  "osVersion" : {
    "train" : "macOS 12.6.2",
    "build" : "21G320",
    "releaseType" : "User"
  },
  "captureTime" : "2022-12-27 10:09:33.9932 -0500",
  "incident" : "69773397-6A4F-4B87-8E5D-A45AD707D761",
  "bug_type" : "309",
  "pid" : 3246,
  "procExitAbsTime" : 9532324261838,
  "cpuType" : "X86-64",
  "procName" : "nwjs",
  "procPath" : "\/private\/var\/folders\/*\/Snap4Arduino.app\/Contents\/MacOS\/nwjs",
  "bundleInfo" : {"CFBundleShortVersionString":"Version 7.0.4","CFBundleVersion":"7.0.4","CFBundleIdentifier":"com.nw-builder.snaparduino"},
  "storeInfo" : {"deviceIdentifierForVendor":"63AD07AC-CF00-5D85-ACB0-55466CB5158C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.nw-builder.snaparduino",
  "crashReporterKey" : "E340F9B8-87D7-D073-FFC1-12221F22D2A9",
  "wakeTime" : 4547,
  "sleepWakeUUID" : "30E4426F-D7D0-43D2-A2B3-1BCB74515469",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":106974,"threadState":{"r13":{"value":140191935250720},"rax":{"value":0},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":6},"rsi":{"value":6},"r8":{"value":140704321125528,"symbolLocation":456,"symbol":"__sFX"},"cr2":{"value":4556738560},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":22},"rbx":{"value":4820796928,"symbolLocation":0,"symbol":"_main_thread"},"trap":{"value":133},"err":{"value":33554760},"r11":{"value":582},"rip":{"value":140703222702094,"matchesCrashFrame":1},"rbp":{"value":140701793466256},"rsp":{"value":140701793466216},"r12":{"value":259},"rcx":{"value":140701793466216},"flavor":"x86_THREAD_STATE","rdi":{"value":259}},"queue":"com.apple.main-thread","frames":[{"imageOffset":32782,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":0},{"imageOffset":25087,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":1},{"imageOffset":531748,"symbol":"abort","symbolLocation":123,"imageIndex":2},{"imageOffset":532114,"symbol":"abort_report_np","symbolLocation":180,"imageIndex":2},{"imageOffset":2504,"symbol":"main","symbolLocation":536,"imageIndex":3},{"imageOffset":2205,"symbol":"main","symbolLocation":237,"imageIndex":3},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703222669312,
    "size" : 229376,
    "uuid" : "07ad083c-2835-3d18-bb6d-6f081840c8a4",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703222898688,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703221653504,
    "size" : 561152,
    "uuid" : "e42e9d7a-03b4-340b-b61e-dcd45fd4acc0",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4555321344,
    "CFBundleShortVersionString" : "Version 7.0.4",
    "CFBundleIdentifier" : "com.nw-builder.snaparduino",
    "size" : 253952,
    "uuid" : "4c4c44d6-5555-3144-a1bb-b4753f1fb10b",
    "path" : "\/private\/var\/folders\/*\/Snap4Arduino.app\/Contents\/MacOS\/nwjs",
    "name" : "nwjs",
    "CFBundleVersion" : "7.0.4"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4820271104,
    "size" : 442368,
    "uuid" : "b53641ea-6cd4-39c9-9b14-59c92cfd9584",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703219642368,
  "size" : 19331678208,
  "uuid" : "3172f8f5-c412-3210-95e0-1cfd89e01f8a"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=138.9M resident=0K(0%) swapped_out_or_unallocated=138.9M(100%)\nWritable regions: Total=26.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=26.1M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nKernel Alloc Once                    8K        1 \nMALLOC                            18.1M        9 \nMALLOC guard page                   16K        4 \nObjC additional data                15K        1 \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                             210K       39 \n__DATA_CONST                       288K       33 \n__DATA_DIRTY                        58K       22 \n__LINKEDIT                       133.9M        4 \n__TEXT                            5060K       43 \ndyld private memory               1024K        1 \nshared memory                        8K        1 \n===========                     =======  ======= \nTOTAL                            222.5M      163 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000234
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac16,2, BootROM 476.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3.1 GHz, 8 GB, SMC 2.32f21
Graphics: Intel Iris Pro Graphics 6200, Intel Iris Pro Graphics 6200, Built-In
Display: iMac, 4096 x 2304 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x156), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB30Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub in Apple Extended USB Keyboard
USB Device: Apple Extended USB Keyboard
USB Device: Apple Optical USB Mouse
Thunderbolt Bus: iMac, Apple Inc., 27.4

**Comment by jguille2** [comment] 2022-12-27 16:33
Hi @danadak  (also I ping @rkoonz2 who had a related issue).

First, sorry but I can't test anything on Macs... because I haven't any apple device :(
Then I need your feedback. The only thing I can say now is that we have a lot of MacVersion downloads (thousands), and only these two issues... So I guess it is running in a lot of Mac devices right now.
Three comments:

1. I see there is the "Error Code: 0x02000148", and it seems that it is related about launching  "unauthorized" or unsigned applications. Maybe the problem is here? Maybe you have to inform to your system that you want to allow them to be installed.
I see some pages talking about "Allow apps downloaded from 'anywhere'", that it is needed... But as I said, I'm not a Mac user and I'm not sure about this.
3. Please. Test this (trying to allow "anywhere apps") with our latest versions (7.0.4 and also with 6.2). If you can't... tell me, but I'm going to release Snap4Arduino8.1 in the coming days. So, if the problem continue... I will want to test with you with that new version... And, if needed, I will look for more information and test with you to try to fix it.
4. In the meantime... You know you can use the online version, don't you?
Just download our Snap4Arduino connector (https://github.com/bromagosa/Snap4Arduino/releases/download/7.0.4/Snap4Arduino_web_connector_crx_7.0.zip) and install it in your Chromium/Chrome/Edge browser (using chrome://extensions and developer mode)
Then, http://snap4arduino.rocks/run will connect with your Arduino-Firmata devices.

Joan

**Comment by danadak** [comment] 2022-12-27 22:13
I myself a new user to Apple. Now its giving me an opening screen I need a subscription.

Not a clue what that about. Steve Jobs still controlling US from the grave.

I will be happy to test with new version. Note version I installed latest on website.


Regards, Dana.

**Comment by edgarallan** [comment] 2023-01-25 00:36
Hi, 
I've got the same error with mac mini M1 12.6.2 (monterey) and other M1 macs running monterey.
No way to start the application: it continues to quit unexpectedly 
I think it is a problem related to unsigned application.
Please let me know
Thanks

**Comment by jguille2** [comment] 2023-01-25 02:16
Hi!
Sorry... and yes, I think unsigned application is related...
I asked for a mac  for testing... but I still don't have it. I hope next week I'll be able to test (and try to fix something in our building). But we'll still be an unsigned ap...because we do not have the capacity to pay to enter the Apple ecosystem.

In the meantime, I guess you know you can run our Snap4Arduino online, don't you?

Joan

**Comment by jguille2** [comment] 2023-01-28 00:30
Hi @danadak and @edgarallan !

https://github.com/bromagosa/Snap4Arduino/issues/317#issuecomment-1407217193

I think the "mac issue" is gone.

Great if you can test and report feedback. Thanks!

Joan

**Comment by jguille2** [comment] 2023-05-25 09:41
Some other tests confirm Mac issue is gone... also in the newest release.
Closing...

**Closed as completed by jguille2** 2023-05-25 09:41 UTC
