### ISSUE TITLE
"arduino not connected" using "Tell Sprite to"

### ISSUE THREAD

**Issue by DavidGasku** [bromagosa/Snap4Arduino#219] opened 2018-01-12 11:37 UTC
I have one object connected to arduino. If another object wants to interact with it, I use the "Tell to" with some arduino block. I would expect this block to be run under the arduino sprite's context, but it is throwing me the "arduino not connected" error.

![indice](https://user-images.githubusercontent.com/5382201/34873309-e50b6b60-f794-11e7-8c49-1e72fb41c61a.png)

Is this supposed to work like this? If so, any way to workaround this problem?

Thanks!

**Comment by jguille2** [comment] 2018-01-12 12:07
Thanks @DavidGasku for your report.

I see the problem!

We must to change our check
```javascript
var sprite = this.homeContext.receiver;
```
for this other
```javascript
var sprite = this.blockReceiver();
```
and then, calling an Arduino function from other Sprite will run ok.

I'll change this and it will be fix in the next version (soon).

Joan

**Comment by DavidGasku** [comment] 2018-01-12 14:22
Thanks Joan.

**Comment by jguille2** [comment] 2018-01-13 00:42
The issue is fixed for the next version. It will be soon to be able to enjoy with Snap 4.1.x

So, I close this issue. Thanks for reporting it!

Joan

**Closed as completed by jguille2** 2018-01-13 00:42 UTC
