### ISSUE TITLE
Problems with http server

### ISSUE THREAD

**Issue by ToonTalk** [bromagosa/Snap4Arduino#180] opened 2017-08-15 10:53 UTC
After enabling the http server (which by the way should be mentioned on http://snap4arduino.org/#http) I see

![image](https://user-images.githubusercontent.com/2138696/29312995-e724c53e-81b7-11e7-936b-8b2be6ba663c.png)

Entering these URLs into any browser (I tried Chrome, FireFox, and Edge) always takes me to the search page. When I tried to open one of these URLs from inside of Snap (using the http block) I see an error "".

![image](https://user-images.githubusercontent.com/2138696/29313061-2bdaabda-81b8-11e7-890e-ad078b8a8331.png)

However when I tried http://localhost:42001/broadcast=m it worked

**Comment by ToonTalk** [comment] 2017-08-15 11:43
Also is it possible for the Snap4Arduino Chrome extension to support the http server?

**Comment by jguille2** [comment] 2018-02-13 22:19
Hey,
I close this because the issue is fixed in 1.2.5 (next Friday!) and now that dialog shows only ipv4 IPs.

And I had already written down the possibility of adding httpserver feature into web version (into the plugin)... That is in my TODO large list :)

**Closed as completed by jguille2** 2018-02-13 22:19 UTC
