### ISSUE TITLE
Tone()

### ISSUE THREAD

**Issue by Seven7au** [bromagosa/Snap4Arduino#141] opened 2017-03-09 11:42 UTC
Does anyone have a tone block which they have developed? To play a tone on an external buzzer. It would really help me out.

**Comment by jguille2** [comment] 2017-03-09 12:03
Hi @Seven7au ,

You can take a look at [this project](https://github.com/jguille2/SA5/blob/master/firmata/SA5Firmata.md).

The problem is StandardFirmata has not ToneFunction implemented. Then you have to run block that use an extended firmata.

In this project, you can use SA5Firmata_tone 2.0, implementing Tone standard function into Arduino. The main version (SA5Firmata) use a blocking (more limitated) tone function that allows to use it with IR libraries (IR and Tone use the same timer).

Joan

**Comment by Seven7au** [comment] 2017-03-10 10:43
Wow, you have sure done a lot of work there. Well done, and thanks for your help again Joan.
Cheers, 
Seven

**Comment by bromagosa** [comment] 2017-04-03 08:53
Thanks @jguille2 for responding to this one too :)

Closing it now.

**Closed as completed by bromagosa** 2017-04-03 08:53 UTC
