### ISSUE TITLE
Long start

### ISSUE THREAD

**Issue by raffoux** [bromagosa/Snap4Arduino#206] opened 2017-11-08 19:36 UTC
Hello

Since snaparduino version 1.2.3, the software takes a long time to start, it is probably caused by the change of the address of the snaparduino website. The software tries to download a file at the old address.

![snap_start](https://user-images.githubusercontent.com/19383543/32570415-5bccf560-c4c4-11e7-9c63-21b41ef18ebc.png)

I use the 32 or 64-bit linux version with my students.
Thank you for this excellent software.

**Comment by jguille2** [comment] 2017-11-08 21:47
Yes, you are right.

But you must upgrade to [1.2.4](https://github.com/bromagosa/Snap4Arduino/releases/tag/1.2.4) (released in October 19th) that fixes this delay caused by the website domain change.

Thanks,
Joan

**Closed as completed by jguille2** 2017-11-08 21:47 UTC

**Comment by raffoux** [comment] 2017-11-16 13:06
Thanks,
Jean-Christophe
