### ISSUE TITLE
distance sensor not working

### ISSUE THREAD

**Issue by woronin** [bromagosa/Snap4Arduino#318] opened 2023-01-29 09:07 UTC
When connecting an ultrasonic distance sensor, an error pops up.
This error began to appear only in new versions - 7.0.4
If you run the same program in version 6.2, then there are no errors
![image](https://user-images.githubusercontent.com/18325725/215316281-27a82ef8-5d14-4ad0-9256-fecbf3de2a05.png)
[7_04_distant2.xml.tar.gz](https://github.com/bromagosa/Snap4Arduino/files/10529417/7_04_distant2.xml.tar.gz)

**Comment by jguille2** [comment] 2023-01-29 11:56
Hi @woronin

This is not a bug. I explain the current operation and the different possibilities:

1. Snap! (and then Snap4Arduino) decided not to execute generic javascript code without the user's permission, to prevent bad practices (especially considering the execution of projects that are made directly from the web, to test them, without seeing the code or knowing who has done). And yes, this happened at version 7.
But you only have to go to Snap4Arduino settings menu, and click to allow "Javascript extensions". And that's all.

![allowJs](https://user-images.githubusercontent.com/2926315/215324428-a7946984-c03a-4060-bcb6-5f7b514a73b6.png)

2. If you want to avoid this requeriment (having to enable the extensions each time) you still have two options:
  2.1 You have libraries that have this "ping" block implemented. I use SA5Firmata, and then, this SA5Firmata library has this block (and others: tone, pulses, nunchuck and dht11). You can use that "ping" block or you can use the generic "pulseIn" block to build your own.

![pingBlock](https://user-images.githubusercontent.com/2926315/215324236-752fc1f1-22bb-4340-9dc4-98eecdd4889a.png)

  2.2 If you use another Firmata code to implement this ping option, you can take a look at the Snap4Arduino "primitives" because we set different "general used options" to allow these "javascript known code" without extensions. These functions are at https://github.com/bromagosa/Snap4Arduino/blob/master/src/s4a/extensions.js#L117-L215

That's all.
I close this issue, but you continue if needed with questions or suggestions.

Joan

**Closed as completed** 2023-01-29 11:56 UTC
